<a href="https://colab.research.google.com/github/Mostafa-Seyedi/pytorch-fundamentals/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch fundamentals
Resource notebook: https://www.learnpytorch.io/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu128


### Introduction to tensors

## Creating tensors

Pytorch tensors are created using 'torch.Tensor() = "https://docs.pytorch.org/docs/stable/tensors.html"



In [ ]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

10

In [ ]:
# Vector
vector = torch.tensor([10,10])
vector

tensor([10, 10])

In [ ]:
vector.ndim

1

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2],
                        [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
# TENSOR
TENSOR = torch.tensor([
                        [[1,2,3],
                        [4,5,6],
                        [7,8,9]],

                       [[11,12,13],
                        [14,15,16],
                        [17,18,19]],

                       [[21,22,23],
                        [24,25,26],
                        [27,28,29]]
                       ],)
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[21, 22, 23],
         [24, 25, 26],
         [27, 28, 29]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([3, 3, 3])

### Random tensors

Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to represent the data better.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

torch random tensors - "https://docs.pytorch.org/docs/stable/generated/torch.rand.html"

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2605, 0.8947, 0.0916, 0.6984],
        [0.1655, 0.0824, 0.9474, 0.3283],
        [0.6334, 0.4514, 0.5197, 0.0051]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
# "size" can be eliminated without any problem
random_image_tensor = torch.rand(size=(3, 224,224)) #  color channels (R,G,B), height, width
random_image_tensor

tensor([[[0.2318, 0.5781, 0.9409,  ..., 0.0108, 0.6632, 0.2224],
         [0.2046, 0.1664, 0.5308,  ..., 0.6046, 0.6495, 0.1527],
         [0.3724, 0.0913, 0.1689,  ..., 0.6724, 0.8937, 0.6738],
         ...,
         [0.9434, 0.1600, 0.0929,  ..., 0.0597, 0.5296, 0.4898],
         [0.0811, 0.6139, 0.7375,  ..., 0.9558, 0.3094, 0.2236],
         [0.0453, 0.1045, 0.3727,  ..., 0.1856, 0.1481, 0.8709]],

        [[0.4003, 0.0649, 0.7081,  ..., 0.9811, 0.7749, 0.8942],
         [0.0839, 0.1582, 0.4853,  ..., 0.9627, 0.5648, 0.7904],
         [0.7960, 0.8081, 0.0573,  ..., 0.4389, 0.1280, 0.0512],
         ...,
         [0.5855, 0.8513, 0.6664,  ..., 0.0446, 0.1533, 0.5491],
         [0.9975, 0.4339, 0.1990,  ..., 0.0660, 0.8133, 0.9838],
         [0.0733, 0.6327, 0.3491,  ..., 0.8471, 0.3988, 0.9510]],

        [[0.3462, 0.4326, 0.9815,  ..., 0.4278, 0.0778, 0.1379],
         [0.4054, 0.6075, 0.5539,  ..., 0.6905, 0.8975, 0.5171],
         [0.4354, 0.6540, 0.9894,  ..., 0.5356, 0.9620, 0.

### Zeros and Ones tensors

In [ ]:
z_tensor = torch.zeros(2,4)
z_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
o_tensor = torch.ones(8,4)
o_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors & tensors-like

In [ ]:
a = torch.arange(10)

In [ ]:
torch.arange(5,100,5)

tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
        95])

In [ ]:
# Creating tensors-like
all_zero = torch.zeros_like(a)
all_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into with pyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device  

In [ ]:
tens_1 = torch.tensor([3.0, 4.0, 5.0],
                      dtype=None,   # what is the datatype of the tensor(e.g. float32, float16)
                      device=None,  # what device is our tensor on (e.g. cpu or cuda)
                      requires_grad=False) # whether or not to track gradients with this tensor operations

tens_2 = torch.tensor([1.0,2.0,3.0], dtype=torch.float16)


In [ ]:
tens_1.dtype

torch.float32

In [ ]:
tens_1*tens_2

tensor([ 3.,  8., 15.])

### Getting info from a tensor
1. tensor.dtype
2. tensor.shape  OR tensor.size
3. tensor.device

In [ ]:
# Device of tens_1
tens_1.device

device(type='cpu')

### Manipulating Tensors (tensor operations)

1. Addition
2. Subtraction
3. Element-wise multiplication
4. Division
5. Matrix multiplication

In [ ]:
tensor_a = torch.rand(2,3)
tensor_b = torch.rand(2,3)

In [ ]:
torch.mul(tensor_a, tensor_b) # Element wise multiplication (also can be like: tensor_a * tensor_b)

tensor([[0.0490, 0.0819, 0.8288],
        [0.0725, 0.1426, 0.1653]])

In [ ]:
%%time
tensor_a @ tensor_b.T # Matrix multiplication (It is the same as: matmul(tensor_a,tensor_b.T))

CPU times: user 1.64 ms, sys: 104 µs, total: 1.74 ms
Wall time: 18.5 ms


tensor([[0.9597, 0.2316],
        [1.2691, 0.3804]])

### Finding min, max, mean, std, sum and etc of a tensor (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10).reshape(2,5)
x

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [ ]:
x.min() # OR torch.min(x)

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
# mean operation work with float and long dtype only
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

### Squeezing and unsqueezing
1. Squeeze --> remove all 1 dimensions from a tensor
2. Unsqueeze --> add all 1 dimension to a target tensor
3. Permute --> Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
y = torch.arange(10,201,10)

In [ ]:
y

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
        150, 160, 170, 180, 190, 200])

In [ ]:
r = y.view(1,20)

In [ ]:
r.size()

torch.Size([1, 20])

In [ ]:
r = r.squeeze()

In [ ]:
r.size()

torch.Size([20])

In [ ]:
rs = r.unsqueeze(dim=1)

In [ ]:
rs.shape

torch.Size([20, 1])

In [ ]:
x_original = torch.rand(size=(224,224,3))

In [ ]:
x_original.permute(2,0,1).shape  # shift axis 0->1, 1->2, 2->0

torch.Size([3, 224, 224])

### Indexing

x[matrix, rows, columns]

PyTorch tensors & Numpy

In [ ]:
import numpy as np
array = np.arange(0,11)
tensor = torch.from_numpy(array)
array, tensor

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
# The point is that the default type for a numpy array is int64 or float64, while if we create a tensor, its default type is float32 or int32
tensor.dtype

torch.int64

In [ ]:
# Another point is that when we use "from_numpy" a separated tensor will be created so mudification in the array will not affect the tensor
array = array + 1
array, tensor

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

### Running tensors and PyTorch objects on the GPUs

GPUs = faster computation on number, thanks to CUDA and NVIDIA hardware.

1. Use google Colab
2. Use your own GPU, which required a little bit of setup
3. Use cloud computing like GCP, AWS, Azure ...

**To check the connection to the GPU, we can use the "!nvidia-smi" command**

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code (run on GPU if its available, else default to CPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors(and models) on the GPU

Using GPU --> faster computations



In [ ]:
tensor = torch.tensor([1,2,3], device="cpu") # by default it is on CPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move the tensor to GPU (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

- As Numpy doesn't work work GPU, we can't transform a tensor on GPU to Numpy

- To do so, we need first to set the tensor to CPU


In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])